# Generated by Django 4.1 on 2022-09-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fabricante', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('cant_dosis', models.IntegerField()),
            ],
        ),
    ]
